### ISSUE TITLE
Error in Ruby 3

### ISSUE THREAD

**Issue by jnylen** [janko-m/shrine-imgix#8]
Due to the kwargs changes, we are getting this:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
from /home/rtxde/.local/share/rtx/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/shrine-imgix-0.5.2/lib/shrine/plugins/imgix.rb:22:in `imgix_url'
```

When passing in: 
```
Image.first.file.imigx_url({w: 200})
```

**Comment by jnylen** [comment]
Fixed by just bypassing it with `**params`

**Comment by janko** [comment]
Yes, as of Ruby 3 hashes and kwargs aren't interchangeable, and the documentation shows kwargs.

**Comment by jnylen** [comment]
@janko yeah, just dropped this here in case someone else got the same issue. :)
